name: Publish to Testflight

on:
  release:
    types: [created]

jobs:
  publish-to-testflight:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: expo/expo-github-action@v4
        with:
          expo-username: ${{secrets.EXPO_CLI_USERNAME}}
          expo-password: ${{secrets.EXPO_CLI_PASSWORD}}
          expo-packager: yarn
      - name: Install deps
        run: yarn install
      - name: Build iOS app
        run: expo build:ios
        env:
            EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
            EXPO_APPLE_ID_PASSWORD: ${{secrets.EXPO_APPLE_ID_PASSWORD}}
      - name: Upload iOS app
        run: expo upload:ios --app-name "[SET THIS TO YOUR APP NAME]"
        env:
            EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
            EXPO_APPLE_ID_PASSWORD: ${{secrets.EXPO_APPLE_ID_PASSWORD}}
